-- =====================================================
-- SCRIPT DE IMPORTAÇÃO DE PRODUTOS
-- Importa os 120 produtos do catálogo para o banco
-- =====================================================

USE usetrafo_db;

-- Limpar produtos existentes (OPCIONAL - descomente se quiser limpar antes)
-- DELETE FROM produtos;

-- =====================================================
-- TRANSFORMADORES A ÓLEO - MÉDIA TENSÃO (42 produtos)
-- =====================================================

-- 45 kVA
INSERT INTO produtos (id, nome, descricao, descricao_completa, subtitulo, preco, categoria, slug, especificacoes, imagem_principal, imagens, ativo, tags) VALUES
(UUID(), 'Transformador a Óleo 45 kVA – Classe 15 kV', 'Transformador a óleo de média tensão 45 kVA classe 15 kV', '<p>Transformador a óleo de 45 kVA classe 15 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 45 kVA classe 15 kV', 10700.00, 'transformadores-oleo', 'transformador-oleo-45kva-classe-15kv', '{"potencia": "45 kVA", "classe": "15 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg", "src/imgs/trafos a seco2.jpeg", "src/imgs/trafos a seco3.jpeg"]', TRUE, '["transformador", "oleo", "45kVA", "15kV"]'),
(UUID(), 'Transformador a Óleo 45 kVA – Classe 25 kV', 'Transformador a óleo de média tensão 45 kVA classe 25 kV', '<p>Transformador a óleo de 45 kVA classe 25 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 45 kVA classe 25 kV', 11400.00, 'transformadores-oleo', 'transformador-oleo-45kva-classe-25kv', '{"potencia": "45 kVA", "classe": "25 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg", "src/imgs/trafos a seco2.jpeg"]', TRUE, '["transformador", "oleo", "45kVA", "25kV"]'),
(UUID(), 'Transformador a Óleo 45 kVA – Classe 36 kV', 'Transformador a óleo de média tensão 45 kVA classe 36 kV', '<p>Transformador a óleo de 45 kVA classe 36 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 45 kVA classe 36 kV', 13600.00, 'transformadores-oleo', 'transformador-oleo-45kva-classe-36kv', '{"potencia": "45 kVA", "classe": "36 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "45kVA", "36kV"]'),

-- 75 kVA
(UUID(), 'Transformador a Óleo 75 kVA – Classe 15 kV', 'Transformador a óleo de média tensão 75 kVA classe 15 kV', '<p>Transformador a óleo de 75 kVA classe 15 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 75 kVA classe 15 kV', 14900.00, 'transformadores-oleo', 'transformador-oleo-75kva-classe-15kv', '{"potencia": "75 kVA", "classe": "15 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "75kVA", "15kV"]'),
(UUID(), 'Transformador a Óleo 75 kVA – Classe 25 kV', 'Transformador a óleo de média tensão 75 kVA classe 25 kV', '<p>Transformador a óleo de 75 kVA classe 25 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 75 kVA classe 25 kV', 15900.00, 'transformadores-oleo', 'transformador-oleo-75kva-classe-25kv', '{"potencia": "75 kVA", "classe": "25 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "75kVA", "25kV"]'),
(UUID(), 'Transformador a Óleo 75 kVA – Classe 36 kV', 'Transformador a óleo de média tensão 75 kVA classe 36 kV', '<p>Transformador a óleo de 75 kVA classe 36 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 75 kVA classe 36 kV', 17600.00, 'transformadores-oleo', 'transformador-oleo-75kva-classe-36kv', '{"potencia": "75 kVA", "classe": "36 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "75kVA", "36kV"]'),

-- 112.5 kVA
(UUID(), 'Transformador a Óleo 112.5 kVA – Classe 15 kV', 'Transformador a óleo de média tensão 112.5 kVA classe 15 kV', '<p>Transformador a óleo de 112.5 kVA classe 15 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 112.5 kVA classe 15 kV', 18300.00, 'transformadores-oleo', 'transformador-oleo-1125kva-classe-15kv', '{"potencia": "112.5 kVA", "classe": "15 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "112.5kVA", "15kV"]'),
(UUID(), 'Transformador a Óleo 112.5 kVA – Classe 25 kV', 'Transformador a óleo de média tensão 112.5 kVA classe 25 kV', '<p>Transformador a óleo de 112.5 kVA classe 25 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 112.5 kVA classe 25 kV', 19500.00, 'transformadores-oleo', 'transformador-oleo-1125kva-classe-25kv', '{"potencia": "112.5 kVA", "classe": "25 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "112.5kVA", "25kV"]'),
(UUID(), 'Transformador a Óleo 112.5 kVA – Classe 36 kV', 'Transformador a óleo de média tensão 112.5 kVA classe 36 kV', '<p>Transformador a óleo de 112.5 kVA classe 36 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 112.5 kVA classe 36 kV', 20800.00, 'transformadores-oleo', 'transformador-oleo-1125kva-classe-36kv', '{"potencia": "112.5 kVA", "classe": "36 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "112.5kVA", "36kV"]'),

-- 150 kVA
(UUID(), 'Transformador a Óleo 150 kVA – Classe 15 kV', 'Transformador a óleo de média tensão 150 kVA classe 15 kV', '<p>Transformador a óleo de 150 kVA classe 15 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 150 kVA classe 15 kV', 22400.00, 'transformadores-oleo', 'transformador-oleo-150kva-classe-15kv', '{"potencia": "150 kVA", "classe": "15 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "150kVA", "15kV"]'),
(UUID(), 'Transformador a Óleo 150 kVA – Classe 25 kV', 'Transformador a óleo de média tensão 150 kVA classe 25 kV', '<p>Transformador a óleo de 150 kVA classe 25 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 150 kVA classe 25 kV', 23700.00, 'transformadores-oleo', 'transformador-oleo-150kva-classe-25kv', '{"potencia": "150 kVA", "classe": "25 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "150kVA", "25kV"]'),
(UUID(), 'Transformador a Óleo 150 kVA – Classe 36 kV', 'Transformador a óleo de média tensão 150 kVA classe 36 kV', '<p>Transformador a óleo de 150 kVA classe 36 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 150 kVA classe 36 kV', 26000.00, 'transformadores-oleo', 'transformador-oleo-150kva-classe-36kv', '{"potencia": "150 kVA", "classe": "36 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "150kVA", "36kV"]'),

-- 225 kVA
(UUID(), 'Transformador a Óleo 225 kVA – Classe 15 kV', 'Transformador a óleo de média tensão 225 kVA classe 15 kV', '<p>Transformador a óleo de 225 kVA classe 15 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 225 kVA classe 15 kV', 29900.00, 'transformadores-oleo', 'transformador-oleo-225kva-classe-15kv', '{"potencia": "225 kVA", "classe": "15 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "225kVA", "15kV"]'),
(UUID(), 'Transformador a Óleo 225 kVA – Classe 25 kV', 'Transformador a óleo de média tensão 225 kVA classe 25 kV', '<p>Transformador a óleo de 225 kVA classe 25 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 225 kVA classe 25 kV', 31700.00, 'transformadores-oleo', 'transformador-oleo-225kva-classe-25kv', '{"potencia": "225 kVA", "classe": "25 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "225kVA", "25kV"]'),
(UUID(), 'Transformador a Óleo 225 kVA – Classe 36 kV', 'Transformador a óleo de média tensão 225 kVA classe 36 kV', '<p>Transformador a óleo de 225 kVA classe 36 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 225 kVA classe 36 kV', 34900.00, 'transformadores-oleo', 'transformador-oleo-225kva-classe-36kv', '{"potencia": "225 kVA", "classe": "36 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "225kVA", "36kV"]'),

-- 300 kVA
(UUID(), 'Transformador a Óleo 300 kVA – Classe 15 kV', 'Transformador a óleo de média tensão 300 kVA classe 15 kV', '<p>Transformador a óleo de 300 kVA classe 15 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 300 kVA classe 15 kV', 34600.00, 'transformadores-oleo', 'transformador-oleo-300kva-classe-15kv', '{"potencia": "300 kVA", "classe": "15 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "300kVA", "15kV"]'),
(UUID(), 'Transformador a Óleo 300 kVA – Classe 25 kV', 'Transformador a óleo de média tensão 300 kVA classe 25 kV', '<p>Transformador a óleo de 300 kVA classe 25 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 300 kVA classe 25 kV', 36600.00, 'transformadores-oleo', 'transformador-oleo-300kva-classe-25kv', '{"potencia": "300 kVA", "classe": "25 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "300kVA", "25kV"]'),
(UUID(), 'Transformador a Óleo 300 kVA – Classe 36 kV', 'Transformador a óleo de média tensão 300 kVA classe 36 kV', '<p>Transformador a óleo de 300 kVA classe 36 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 300 kVA classe 36 kV', 39100.00, 'transformadores-oleo', 'transformador-oleo-300kva-classe-36kv', '{"potencia": "300 kVA", "classe": "36 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "300kVA", "36kV"]'),

-- 500 kVA
(UUID(), 'Transformador a Óleo 500 kVA – Classe 15 kV', 'Transformador a óleo de média tensão 500 kVA classe 15 kV', '<p>Transformador a óleo de 500 kVA classe 15 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 500 kVA classe 15 kV', 53500.00, 'transformadores-oleo', 'transformador-oleo-500kva-classe-15kv', '{"potencia": "500 kVA", "classe": "15 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "500kVA", "15kV"]'),
(UUID(), 'Transformador a Óleo 500 kVA – Classe 25 kV', 'Transformador a óleo de média tensão 500 kVA classe 25 kV', '<p>Transformador a óleo de 500 kVA classe 25 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 500 kVA classe 25 kV', 56100.00, 'transformadores-oleo', 'transformador-oleo-500kva-classe-25kv', '{"potencia": "500 kVA", "classe": "25 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "500kVA", "25kV"]'),
(UUID(), 'Transformador a Óleo 500 kVA – Classe 36 kV', 'Transformador a óleo de média tensão 500 kVA classe 36 kV', '<p>Transformador a óleo de 500 kVA classe 36 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 500 kVA classe 36 kV', 63000.00, 'transformadores-oleo', 'transformador-oleo-500kva-classe-36kv', '{"potencia": "500 kVA", "classe": "36 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "500kVA", "36kV"]'),

-- 750 kVA
(UUID(), 'Transformador a Óleo 750 kVA – Classe 15 kV', 'Transformador a óleo de média tensão 750 kVA classe 15 kV', '<p>Transformador a óleo de 750 kVA classe 15 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 750 kVA classe 15 kV', 72100.00, 'transformadores-oleo', 'transformador-oleo-750kva-classe-15kv', '{"potencia": "750 kVA", "classe": "15 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "750kVA", "15kV"]'),
(UUID(), 'Transformador a Óleo 750 kVA – Classe 25 kV', 'Transformador a óleo de média tensão 750 kVA classe 25 kV', '<p>Transformador a óleo de 750 kVA classe 25 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 750 kVA classe 25 kV', 76400.00, 'transformadores-oleo', 'transformador-oleo-750kva-classe-25kv', '{"potencia": "750 kVA", "classe": "25 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "750kVA", "25kV"]'),
(UUID(), 'Transformador a Óleo 750 kVA – Classe 36 kV', 'Transformador a óleo de média tensão 750 kVA classe 36 kV', '<p>Transformador a óleo de 750 kVA classe 36 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 750 kVA classe 36 kV', 84500.00, 'transformadores-oleo', 'transformador-oleo-750kva-classe-36kv', '{"potencia": "750 kVA", "classe": "36 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "750kVA", "36kV"]'),

-- 1000 kVA
(UUID(), 'Transformador a Óleo 1000 kVA – Classe 15 kV', 'Transformador a óleo de média tensão 1000 kVA classe 15 kV', '<p>Transformador a óleo de 1000 kVA classe 15 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 1000 kVA classe 15 kV', 92400.00, 'transformadores-oleo', 'transformador-oleo-1000kva-classe-15kv', '{"potencia": "1000 kVA", "classe": "15 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "1000kVA", "15kV"]'),
(UUID(), 'Transformador a Óleo 1000 kVA – Classe 25 kV', 'Transformador a óleo de média tensão 1000 kVA classe 25 kV', '<p>Transformador a óleo de 1000 kVA classe 25 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 1000 kVA classe 25 kV', 98600.00, 'transformadores-oleo', 'transformador-oleo-1000kva-classe-25kv', '{"potencia": "1000 kVA", "classe": "25 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "1000kVA", "25kV"]'),
(UUID(), 'Transformador a Óleo 1000 kVA – Classe 36 kV', 'Transformador a óleo de média tensão 1000 kVA classe 36 kV', '<p>Transformador a óleo de 1000 kVA classe 36 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 1000 kVA classe 36 kV', 108400.00, 'transformadores-oleo', 'transformador-oleo-1000kva-classe-36kv', '{"potencia": "1000 kVA", "classe": "36 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "1000kVA", "36kV"]'),

-- 1250 kVA
(UUID(), 'Transformador a Óleo 1250 kVA – Classe 15 kV', 'Transformador a óleo de média tensão 1250 kVA classe 15 kV', '<p>Transformador a óleo de 1250 kVA classe 15 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 1250 kVA classe 15 kV', 115600.00, 'transformadores-oleo', 'transformador-oleo-1250kva-classe-15kv', '{"potencia": "1250 kVA", "classe": "15 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "1250kVA", "15kV"]'),
(UUID(), 'Transformador a Óleo 1250 kVA – Classe 25 kV', 'Transformador a óleo de média tensão 1250 kVA classe 25 kV', '<p>Transformador a óleo de 1250 kVA classe 25 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 1250 kVA classe 25 kV', 123400.00, 'transformadores-oleo', 'transformador-oleo-1250kva-classe-25kv', '{"potencia": "1250 kVA", "classe": "25 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "1250kVA", "25kV"]'),
(UUID(), 'Transformador a Óleo 1250 kVA – Classe 36 kV', 'Transformador a óleo de média tensão 1250 kVA classe 36 kV', '<p>Transformador a óleo de 1250 kVA classe 36 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 1250 kVA classe 36 kV', 135600.00, 'transformadores-oleo', 'transformador-oleo-1250kva-classe-36kv', '{"potencia": "1250 kVA", "classe": "36 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "1250kVA", "36kV"]'),

-- 1500 kVA
(UUID(), 'Transformador a Óleo 1500 kVA – Classe 15 kV', 'Transformador a óleo de média tensão 1500 kVA classe 15 kV', '<p>Transformador a óleo de 1500 kVA classe 15 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 1500 kVA classe 15 kV', 127600.00, 'transformadores-oleo', 'transformador-oleo-1500kva-classe-15kv', '{"potencia": "1500 kVA", "classe": "15 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "1500kVA", "15kV"]'),
(UUID(), 'Transformador a Óleo 1500 kVA – Classe 25 kV', 'Transformador a óleo de média tensão 1500 kVA classe 25 kV', '<p>Transformador a óleo de 1500 kVA classe 25 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 1500 kVA classe 25 kV', 135600.00, 'transformadores-oleo', 'transformador-oleo-1500kva-classe-25kv', '{"potencia": "1500 kVA", "classe": "25 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "1500kVA", "25kV"]'),
(UUID(), 'Transformador a Óleo 1500 kVA – Classe 36 kV', 'Transformador a óleo de média tensão 1500 kVA classe 36 kV', '<p>Transformador a óleo de 1500 kVA classe 36 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 1500 kVA classe 36 kV', 149100.00, 'transformadores-oleo', 'transformador-oleo-1500kva-classe-36kv', '{"potencia": "1500 kVA", "classe": "36 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "1500kVA", "36kV"]'),

-- 2000 kVA
(UUID(), 'Transformador a Óleo 2000 kVA – Classe 15 kV', 'Transformador a óleo de média tensão 2000 kVA classe 15 kV', '<p>Transformador a óleo de 2000 kVA classe 15 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 2000 kVA classe 15 kV', 162600.00, 'transformadores-oleo', 'transformador-oleo-2000kva-classe-15kv', '{"potencia": "2000 kVA", "classe": "15 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "2000kVA", "15kV"]'),
(UUID(), 'Transformador a Óleo 2000 kVA – Classe 25 kV', 'Transformador a óleo de média tensão 2000 kVA classe 25 kV', '<p>Transformador a óleo de 2000 kVA classe 25 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 2000 kVA classe 25 kV', 172500.00, 'transformadores-oleo', 'transformador-oleo-2000kva-classe-25kv', '{"potencia": "2000 kVA", "classe": "25 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "2000kVA", "25kV"]'),
(UUID(), 'Transformador a Óleo 2000 kVA – Classe 36 kV', 'Transformador a óleo de média tensão 2000 kVA classe 36 kV', '<p>Transformador a óleo de 2000 kVA classe 36 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 2000 kVA classe 36 kV', 187300.00, 'transformadores-oleo', 'transformador-oleo-2000kva-classe-36kv', '{"potencia": "2000 kVA", "classe": "36 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "2000kVA", "36kV"]'),

-- 2500 kVA
(UUID(), 'Transformador a Óleo 2500 kVA – Classe 15 kV', 'Transformador a óleo de média tensão 2500 kVA classe 15 kV', '<p>Transformador a óleo de 2500 kVA classe 15 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 2500 kVA classe 15 kV', 203300.00, 'transformadores-oleo', 'transformador-oleo-2500kva-classe-15kv', '{"potencia": "2500 kVA", "classe": "15 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "2500kVA", "15kV"]'),
(UUID(), 'Transformador a Óleo 2500 kVA – Classe 25 kV', 'Transformador a óleo de média tensão 2500 kVA classe 25 kV', '<p>Transformador a óleo de 2500 kVA classe 25 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 2500 kVA classe 25 kV', 215600.00, 'transformadores-oleo', 'transformador-oleo-2500kva-classe-25kv', '{"potencia": "2500 kVA", "classe": "25 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "2500kVA", "25kV"]'),
(UUID(), 'Transformador a Óleo 2500 kVA – Classe 36 kV', 'Transformador a óleo de média tensão 2500 kVA classe 36 kV', '<p>Transformador a óleo de 2500 kVA classe 36 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 2500 kVA classe 36 kV', 234100.00, 'transformadores-oleo', 'transformador-oleo-2500kva-classe-36kv', '{"potencia": "2500 kVA", "classe": "36 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "2500kVA", "36kV"]'),

-- 3000 kVA
(UUID(), 'Transformador a Óleo 3000 kVA – Classe 15 kV', 'Transformador a óleo de média tensão 3000 kVA classe 15 kV', '<p>Transformador a óleo de 3000 kVA classe 15 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 3000 kVA classe 15 kV', 244000.00, 'transformadores-oleo', 'transformador-oleo-3000kva-classe-15kv', '{"potencia": "3000 kVA", "classe": "15 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "3000kVA", "15kV"]'),
(UUID(), 'Transformador a Óleo 3000 kVA – Classe 25 kV', 'Transformador a óleo de média tensão 3000 kVA classe 25 kV', '<p>Transformador a óleo de 3000 kVA classe 25 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 3000 kVA classe 25 kV', 258700.00, 'transformadores-oleo', 'transformador-oleo-3000kva-classe-25kv', '{"potencia": "3000 kVA", "classe": "25 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "3000kVA", "25kV"]'),
(UUID(), 'Transformador a Óleo 3000 kVA – Classe 36 kV', 'Transformador a óleo de média tensão 3000 kVA classe 36 kV', '<p>Transformador a óleo de 3000 kVA classe 36 kV, desenvolvido para aplicações de média tensão com alta confiabilidade e durabilidade.</p><p>Todos os equipamentos produzidos pela USETRAFO são testados em nosso laboratório individualmente, e emitido certificado de garantia com 36 meses contra defeitos de fabricação.</p>', 'Transformador a óleo de média tensão 3000 kVA classe 36 kV', 280900.00, 'transformadores-oleo', 'transformador-oleo-3000kva-classe-36kv', '{"potencia": "3000 kVA", "classe": "36 kV", "frequencia": "50Hz ou 60Hz", "refrigeracao": "oleo", "construcao": "trifasico", "garantia": "36 meses"}', 'src/imgs/trafos a seco1 .jpeg', '["src/imgs/trafos a seco1 .jpeg"]', TRUE, '["transformador", "oleo", "3000kVA", "36kV"]');

-- =====================================================
-- NOTA: Este arquivo contém apenas os 42 produtos de 
-- Transformadores a Óleo. Os outros 78 produtos 
-- (Autotransformadores e Transformadores Isoladores) 
-- podem ser importados usando o script completo que
-- vou criar agora separadamente ou você pode executar
-- em partes devido ao tamanho.
-- =====================================================

SELECT 'Produtos de Transformadores a Óleo importados!' as mensagem;
SELECT COUNT(*) as total_produtos FROM produtos;
